### ISSUE TITLE
catmullRomSplines not found

### ISSUE THREAD

**Issue by thebigsmileXD** [radondev/CinematicX#4]
https://github.com/radondev/CinematicX/blob/9529251f22c772774e7b49ac7f9db332ac2da638/src/radondev/cinematicx/tasks/PlayTask.php#L141

This should be `catmullRomSplinesVector`

**Comment by radondev** [comment]
Fixed in https://github.com/radondev/CinematicX/commit/297602d0efdd5cbcb476cde21296595abe49d2f0
